### ISSUE TITLE
sf45c Point Cloud datatype

### ISSUE THREAD

**Issue by ashwinvk94** [LightWare-Optoelectronics/lightwarelidar2#1]
Hi,

Is there any reason the sf45c datatype was chosen to be sensor_msgs/PointCloud2 instead of sensor_msgs/LaserScan like the sf 40c? Wouldn't it be better to return a complete scan(end to end) in regular intervals?

**Comment by Rob2048** [comment]
Fundamentally the SF45 does not produce continuous scans.

PointCloud2 was assumed to be a more flexible way to receive updates, and adaptable to the requirements of the application.

Are you having issues using this? If so I can look at adding the LaserScan message.

**Comment by ashwinvk94** [comment]
Got it. The datatype is not a problem, but could you look into this https://github.com/LightWare-Optoelectronics/lightwarelidar2/issues/2.

**Comment by nakai-omer** [comment]
@Rob2048 PointCloud2 is not good for slam-toolbox or other nav2 algorithms expecting a LaserScan message type. 
@ashwinvk94 Not sure why you closed this

Created a PR for conditionaly publishing a LaserScan message (sorry for all the linting, if needed I will remove):
https://github.com/LightWare-Optoelectronics/lightwarelidar2/pull/3
