### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by ashwinvk94** [LightWare-Optoelectronics/lightwarelidar2#2]
when I build an new catkin workspace with just this package, the following error comes up:

`This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.`
![1](https://user-images.githubusercontent.com/35679537/131370280-2604aa25-4d68-4b9d-a09c-eb58ef8c5694.png)

**Comment by Rob2048** [comment]
This driver is for ROS2. I see from your screenshot you are using ROS1. I have updated our ROS1 driver to support the SF45/B. You can find that here: https://github.com/LightWare-Optoelectronics/lightwarelidar
